### ISSUE TITLE
looks like something wrong

### ISSUE THREAD

**Issue by bluelovers** [ChrisCarini/jetbrains-auto-power-saver#1] opened 2019-04-03 14:14 UTC
![image](https://user-images.githubusercontent.com/167966/55485851-d9f26700-565d-11e9-8556-323c8ef1810e.png)

**Comment by ChrisCarini** [comment] 2019-04-03 22:46
Thanks for reporting this @bluelovers - can you provide a bit more details about your environment? (OS, IDE, IDE version, etc)

**Comment by bluelovers** [comment] 2019-04-04 09:58
![image](https://user-images.githubusercontent.com/167966/55547112-3065b100-5703-11e9-9c78-f83088c503c5.png)

win 10

**Comment by ChrisCarini** [comment] 2019-04-11 05:29
Hey @bluelovers, to the left of `IntelliJ IDEA`, there is a (hidden) icon that will copy your information to the clipboard making it easier to paste. Below is a screenshot of said hidden button, and my output.
**Screenshot:**
<img width="399" alt="Screen Shot 2019-04-10 at 22 25 25" src="https://user-images.githubusercontent.com/6374067/55932779-e89dc880-5bdf-11e9-905a-54af789e4654.png">

**Output:**
```
IntelliJ IDEA 2019.1 (Community Edition)
Build #IC-191.6183.87, built on March 26, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

Unfortunately, I'm not sure from your output which build you're using (the JBR8 or JBR11), and I'm not able to reproduce with the latest EAP/RC (`191.6707.31` as of this comment).

**Comment by ChrisCarini** [comment] 2019-05-27 18:54
Hey @bluelovers ,

Can you please provide the details asked for above? With out that, I'm unable to reproduce your issue to resolve it correctly. If I don't hear back, I'm going to close this issue out.

Best,
Chris

**Comment by ChrisCarini** [comment] 2019-11-29 06:48
Friendly reminder - if I don't hear back by the end of the year, I'm going to just close out this issue.

**Comment by ChrisCarini** [comment] 2020-07-29 09:27
Never heard back, and it's been 'end of year' + 6 months. Closing issue out.

**Closed by ChrisCarini** 2020-07-29 09:27 UTC
Labels: question

**Comment by ChrisCarini** [comment] 2023-09-21 23:22
@all-contributors please add @bluelovers for bug
