### ISSUE TITLE
Not Works on macOS Sonoma 14.1 PHPStorm 2023.2.3 (232.10072.32)

### ISSUE THREAD

**Issue by hryvinskyi** [ChrisCarini/jetbrains-auto-power-saver#248] opened 2023-11-12 07:33 UTC
I can't get this plugin to work, it doesn't switch PHPStorm to power saving mode, and when I switch it power save to on manualy, it doesnt off power saving mode

https://app.screencast.com/2uwpvhcmXf3bX

**Comment by hryvinskyi** [comment] 2023-11-12 08:06
I checked several versions, and for me works only [3.1.1](https://plugins.jetbrains.com/plugin/11941-automatic-power-saver/versions/stable/389849)
not works - [3.1.3](https://github.com/ChrisCarini/jetbrains-auto-power-saver/releases/tag/v3.1.3) , [3.1.2](https://github.com/ChrisCarini/jetbrains-auto-power-saver/releases/tag/v3.1.2)

**Comment by nilsbunger** [comment] 2024-01-30 05:45
Similarly power save doesn't enable for me, on PyCharm 2023.3.3, MacOS 14.1.

**Comment by ChrisCarini** [comment] 2024-01-30 09:55
Hi @hryvinskyi & @nilsbunger - thank you both for reporting this; it certainly appears to be a bug/regression. I've opened https://github.com/ChrisCarini/jetbrains-auto-power-saver/pull/273 to fix this, and the change should get released in the plugin version targeting 2023.3.3 (https://github.com/ChrisCarini/jetbrains-auto-power-saver/pull/272 ; I will rebase that shortly once https://github.com/ChrisCarini/jetbrains-auto-power-saver/pull/273 gets merged in).

**Comment by ChrisCarini** [comment] 2024-01-30 09:57
@all-contributors
please add @hryvinskyi for bug. 
please add @nilsbunger for bug.

**Closed** 2024-01-30 10:02 UTC

**Comment by ChrisCarini** [comment] 2024-01-30 18:08
Hi @hryvinskyi & @nilsbunger - https://plugins.jetbrains.com/plugin/11941-automatic-power-saver/versions/stable/477278 is now published. Please give this version a try and let me know if you experience any further issues! Thank you, both, again for reporting the issue!

**Comment by hryvinskyi** [comment] 2024-01-30 19:04
Hi @ChrisCarini 

Version 3.2.3 working very well, thanks!

**Comment by nilsbunger** [comment] 2024-02-01 18:13
Thank you so much. This is not in your control, but I haven't been able to download the new version. The plugin marketplace in pycharm keeps showing 3.2.2 as the "latest". I've tried invalidating caches, restarting, etc, but I can't seem to make it see the new version!! So frustrating.

**Comment by hryvinskyi** [comment] 2024-02-01 20:50
> Thank you so much. This is not in your control, but I haven't been able to download the new version. The plugin marketplace in pycharm keeps showing 3.2.2 as the "latest". I've tried invalidating caches, restarting, etc, but I can't seem to make it see the new version!! So frustrating.

I had the same problem, fixed it by deleting plugin and then finding it again install latest version

**Comment by nilsbunger** [comment] 2024-02-01 21:52
@hryvinskyi thank you but it doesn't help. The plugin isn't currently installed but it still says 3.2.2 in the plugin marketplace screen in pycharm.

**Comment by ChrisCarini** [comment] 2024-02-02 04:15
@nilsbunger hmm, this is quite frustrating. According to the plugin page ([link](https://plugins.jetbrains.com/plugin/11941-automatic-power-saver/edit/versions/stable/477278)), 3.2.3 will work with `PyCharm Professional — build 233.14015 — 233.*`; however, I just downloaded PyCharm Pro from JB, and the build version I got was `Build #PY-233.13763.11, built on January 25, 2024` (aka, it's not 'new' enough, despite being the latest on their site), which is also the build version listed on the site: https://www.jetbrains.com/pycharm/download/

What's really strange, is I don't even see a version of PyCharm for `233.14015` in their API anywhere.

Let me ask in the JetBrains Platform developer slack and see if anyone from JetBrains can help me understand what's going on here...

**Comment by nilsbunger** [comment] 2024-02-06 18:53
@ChrisCarini Good call on the version mismatch. That seems to be the issue.

Like your download, I have version 233.13763.11, built on January 25, 2024.

Did you hear anything from the Jetbrains team? Seems like a small mistake on their part.

**Comment by nilsbunger** [comment] 2024-02-28 18:59
@ChrisCarini with Pycharm 2023.3.4 , I was able to get the latest version of the plugin. Thank you! Hopefully this was a one-time mismatch of version numbers by Jetbrains?

**Comment by ChrisCarini** [comment] 2024-02-29 04:07
Hi @nilsbunger - sorry, I haven't had a chance to respond to your previous message.

I confirmed with JetBrains that the version mismatch was in fact the issue, and they opened a ticket to make the UI of their plugin marketplace more clear that this version of the plugin would not actually work (for all plugins, of course, not just this one 😉). A more clear UI/UX on their marketplace is good, IMO. ✅ 

That being said, this is actually a 'by design' implementation detail on how JetBrains releases their various IDEs. Without going into too much detail, not all of their released versions are the same build number (that is, in this specific case, possibly others, PyCharm 2023.3.3 could be a different build version than IntelliJ 2023.3.3 or CLion 2023.3.3 or any other of their IDEs). JetBrains plugins are built against a specific IDE+version (either something more user-friendly like `2023.3.3`, or their actual build numbers like `233.13763.11`) - since I use the 'friendly' version, the gradle plugin resolves this to the specific build version of the IDE I specify (IntelliJ, `IC`) in the plugin. In this release of the plugin, the build version of IntelliJ was _newer_ than the build version of PyCharm, so the version of this plugin I thought would work for *all* JetBrains IDEs, in fact only worked for any build versions that were equal to, or more recent than, the one specified.

In all my OSS plugins, I've historically pinned a specific version of my plugin to a specific release of JetBrains IDEs (just to make it easier for me to test/support).

I've since made a change that should open the version ranges up such that this particular issue you saw shouldn't happen again (🤞 ), although I still only plan to do testing against a single (i.e. the latest) version to make my life easier. For this specific plugin, you can see the change in https://github.com/ChrisCarini/jetbrains-auto-power-saver/commit/c6e722f2002d15a4edda7421d1c612965fd5d0ad - I have automation to make releasing new versions of my plugin easier for me, and I've also updated that accordingly, though I need to wait for a new release to actually test. 🤞 


Thank you again for commenting on this issue, and I'm glad you were able to get the latest version in PyCharm 2023.3.4! 🎉  Please let me know if you have any other feedback (feel free to open a new issue if it differs from this issues topic)!

**Comment by nilsbunger** [comment] 2024-02-29 17:27
@ChrisCarini Thank you, I had noticed the variations in build versions before between the different products. It all makes sense. I love the plugin by the way, I can just leave Pycharm open all day now even when I get pulled into other stuff

**Comment by ChrisCarini** [comment] 2024-03-10 15:29
> Thank you

Of course!

> I had noticed the variations in build versions before between the different products. It all makes sense.

I've personally never noticed it, because I use IntelliJ for all my development. I do appreciate you raising this, though, as it's good to get this feedback from users for other IDEs.

> I love the plugin by the way, I can just leave Pycharm open all day now even when I get pulled into other stuff

Thank you for the kind words! ❤️ 🎉
